import{NextResponse}from"next/server";import{getServerSession}from"next-auth";import{authOptions}from"@/app/api/auth/[...nextauth]/route";import{connectDB}from"@/lib/mongoose";import Click from"@/models/Click";import Campaign from"@/models/Campaign";import Affiliate from"@/models/Affiliate";
export async function GET(req){
  try{const session=await getServerSession(authOptions);if(!session)return NextResponse.json({error:"Unauthorized"},{status:401});await connectDB();const{searchParams}=new URL(req.url);const range=parseInt(searchParams.get("range")||"30");const page=parseInt(searchParams.get("page")||"1");const limit=50;const role=session.user.role;const userId=session.user.id;const since=new Date(Date.now()-range*24*60*60*1000);const query={createdAt:{$gte:since}};let campMap={};
  if(role==="advertiser"){const mc=await Campaign.find({advertiser:userId}).select("_id shareReferrerWithAdvertiser").lean();mc.forEach(c=>{campMap[c._id.toString()]=c.shareReferrerWithAdvertiser;});query.campaignId={$in:mc.map(c=>c._id)};}
  else if(role==="affiliate"){const aff=await Affiliate.findOne({email:session.user.email}).lean();query.affiliateId=aff?._id;}
  else{const ac=await Campaign.find().select("_id shareReferrerWithAdvertiser").lean();ac.forEach(c=>{campMap[c._id.toString()]=c.shareReferrerWithAdvertiser;});}
  const total=await Click.countDocuments(query);
  const clicks=await Click.find(query).sort({createdAt:-1}).skip((page-1)*limit).limit(limit).populate("campaignId","name shortId shareReferrerWithAdvertiser").lean();
  const result=clicks.map(click=>{const cid=click.campaignId?._id?.toString();const shareRef=click.campaignId?.shareReferrerWithAdvertiser||campMap[cid]||false;return{_id:click._id,clickId:click.clickId,campaign:click.campaignId?.name||"—",campaignShortId:click.campaignId?.shortId||"—",publisherId:role==="affiliate"?undefined:(click.affiliateId?.toString()||"—"),device:click.device||"—",os:click.os||"—",country:click.country||"—",ip:role==="admin"?click.ip:undefined,source:click.source||"—",referer:role==="admin"?click.referer:role==="affiliate"?click.referer:shareRef?click.referer:undefined,isBot:click.isBot,isDuplicate:click.isDuplicate,sub1:click.sub1,createdAt:click.createdAt};});
  return NextResponse.json({clicks:result,total,page,pages:Math.ceil(total/limit)});}catch(err){return NextResponse.json({error:err.message},{status:500});}}
